language: bash

matrix:
  include:
    - env: PROJECT=packages/map
    - env: PROJECT=packages/match-route

jobs:
  include:
    - stage: build
      env: PROJECT=packages/map
      script: if bin/build-condition.sh $TRAVIS_COMMIT_RANGE $PROJECT; then bash bin/build.sh $PROJECT; fi
    - stage: build
      env: PROJECT=packages/match-route
      script: if bin/build-condition.sh $TRAVIS_COMMIT_RANGE $PROJECT; then bash bin/build.sh $PROJECT; fi

    - stage: deploy
      env: PROJECT=packages/map
      script: if bin/build-condition.sh $TRAVIS_COMMIT_RANGE $PROJECT; then sudo bash bin/deploy.sh $PROJECT; fi
    - stage: deploy
      env: PROJECT=packages/match-route
      script: if bin/build-condition.sh $TRAVIS_COMMIT_RANGE $PROJECT; then sudo bash bin/deploy.sh $PROJECT; fi

    ### Feature deployment
    - stage: build-feature
      env: PROJECT=packages/map
      script: if bin/build-condition.sh $TRAVIS_COMMIT_RANGE $PROJECT; then bash bin/build-feature.sh $PROJECT; fi

    - stage: deploy-feature
      env: PROJECT=packages/map
      script: if bin/build-condition.sh $TRAVIS_COMMIT_RANGE $PROJECT; then sudo bash bin/deploy-feature.sh $PROJECT; fi

stages:
  - name: build
    if: (branch = master OR branch = ci-cd) AND type != pull_request
  - name: deploy
    if: (branch = master OR branch = ci-cd) AND type != pull_request
  - name: build-feature
    if: type = pull_request
  - name: deploy-feature
    if: type = pull_request