language: bash

services:
# Require docker to be running in the build context
- docker

jobs:
  include:
    - stage: build
      script: echo "build"
    - stage: deploy
      script: echo "deploy"
stages:
  - build
  - deploy