version: "3.7"

services:
  engine:
    build: ./packages/engine-elixir
    environment:
      AMQP_HOST: amqp://rabbitmq
    networks:
      - predictivemovement

networks:
  predictivemovement:
    driver: bridge
    name: predictivemovement
