version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3-management
    tmpfs: /var/lib/rabbitmq
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672
    networks:
      - predictivemovement
  redis:
    image: redis
    container_name: redis
    ports:
      - 127.0.0.1:6379:6379
    networks:
      - predictivemovement
  postgres:
    image: postgres
    environment:
      - PGDATA=/pgtmpfs
      - POSTGRES_PASSWORD=postgres
    ports:
      - 127.0.0.1:5432:5432
    tmpfs: /pgtmpfs
    networks:
      - predictivemovement
  admin-ui:
    build:
      context: ./packages/engine-ui
      args:
        - REACT_APP_MAPBOX_ACCESS_TOKEN=${REACT_APP_MAPBOX_ACCESS_TOKEN}
        - REACT_APP_ENGINE_SERVER=http://localhost:4000
    ports:
      - 127.0.0.1:3000:80
    networks:
      - predictivemovement
  admin-server:
    build: ./packages/engine-server
    environment:
      - AMQP_URL=amqp://rabbitmq
      - POSTNORD_KEY=${POSTNORD_KEY}
      - MINIO_HOST=storage
    ports:
      - 127.0.0.1:4000:4000
    networks:
      - predictivemovement
  driver-interface:
    build: ./packages/driver-interface
    environment:
      - BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - GOOGLE_API_TOKEN=${GOOGLE_API_TOKEN}
      - AMQP_HOST=rabbitmq
      - AMQP_URL=amqp://rabbitmq
      - REDIS_URL=redis://redis:6379
    networks:
      - predictivemovement
  predictivemovement-route-optimization-jsprit:
    build: ./packages/route-optimization-jsprit
    container_name: "predictivemovement_route-optimization-jsprit"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - predictivemovement
  vehicle-offer-router:
    build: ./packages/vehicle-offer
    environment:
      - AMQP_URL=amqp://rabbitmq
    networks:
      - predictivemovement
  auto-accept-offer:
    build: ./packages/auto-accept-offer
    environment:
      - AMQP_URL=amqp://rabbitmq
    networks:
      - predictivemovement
  booking-dispatcher:
    build: ./packages/booking-dispatcher
    environment:
      - AMQP_URL=amqp://rabbitmq
    volumes:
      - ./packages/booking-dispatcher/data:/app/data
    networks:
      - predictivemovement
  storage:
    image: minio/minio
    ports:
      - 127.0.0.1:9000:9000
    command: server /data
    volumes:
      - ./data:/data
    networks:
      - predictivemovement
networks:
  predictivemovement:
    driver: bridge
    name: predictivemovement
