apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: pm-mapbox-test
build:
  artifacts:
    - image: iteam1337/pm-booking-interface
      context: packages/booking-interface
    - image: iteam1337/pm-driver-interface
      context: packages/driver-interface
    - image: iteam1337/pm-engine
      context: packages/elixir_umbrella
      sync:
        infer:
          - "**/*.ex"
          - "**/*.exs"
    - image: iteam1337/pm-engine-server
      context: packages/engine-server
    - image: iteam1337/pm-engine-ui
      context: packages/engine-ui
      docker:
        buildArgs:
          REACT_APP_MAPBOX_ACCESS_TOKEN: "{{.REACT_APP_MAPBOX_ACCESS_TOKEN}}"
          REACT_APP_ENGINE_SERVER: "{{.REACT_APP_ENGINE_SERVER}}"
    - image: iteam1337/pm-plan-graphhopper
      context: packages/plan-graphhopper
    - image: iteam1337/pm-route-optimization-jsprit
      context: packages/route-optimization-jsprit
    - image: iteam1337/pm-vehicle-offer
      context: packages/vehicle-offer
    - image: iteam1337/pm-auto-accept-offer
      context: packages/auto-accept-offer
    - image: iteam1337/pm-booking-dispatcher
      context: packages/booking-dispatcher
deploy:
  kubectl:
    manifests:
      # - k8s/packages/dev/booking-interface.yaml # Disabled until needed again since we use the admin-ui for creating bookings
      - k8s/packages/dev/driver-interface.yaml
      - k8s/packages/dev/engine.yaml
      - k8s/packages/dev/engine-server.yaml
      - k8s/packages/dev/engine-ui.yaml
      - k8s/packages/dev/plan-graphhopper.yaml
      - k8s/packages/dev/route-optimization-jsprit.yaml
      - k8s/packages/dev/vehicle-offer.yaml
      - k8s/packages/dev/auto-accept-offer.yaml
      - k8s/packages/dev/booking-dispatcher.yaml
    # TODO: Disabled because this should be done once and not redeployed every time
    # - k8s/cicd-rbac.yaml
    # - k8s/rabbitmq.yaml
    # - k8s/redis.yaml
    # - k8s/osrm.yaml
    flags:
      global:
        - --namespace=predictivemovement-dev
profiles:
  - name: prod
    # TODO: this is the nicer way to do things so disabled until we learn how to
    # update ingress hosts without duplication of files
    # patches:
    #   - op: replace
    #     path: /deploy/kubectl/flags/global/0
    #     value: --namespace=predictivemovement
    deploy:
      kubectl:
        manifests:
          - k8s/packages/prod/booking-interface.yaml
          - k8s/packages/prod/driver-interface.yaml
          - k8s/packages/prod/engine.yaml
          - k8s/packages/prod/engine-server.yaml
          - k8s/packages/prod/engine-ui.yaml
          - k8s/packages/prod/plan-graphhopper.yaml
          - k8s/packages/prod/route-optimization-jsprit.yaml
          - k8s/packages/prod/vehicle-offer.yaml
          - k8s/packages/prod/auto-accept-offer.yaml
          - k8s/packages/prod/booking-dispatcher.yaml
        flags:
          global:
            - --namespace=predictivemovement
