apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: pm-mapbox-test
build:
  artifacts:
    - image: iteam1337/pm-booking-simulator
      context: packages/booking-simulator
    - image: iteam1337/pm-car-simulator
      context: packages/car-simulator
    - image: iteam1337/pm-booking-interface
      context: packages/booking-interface
    - image: iteam1337/pm-driver-interface
      context: packages/driver-interface
    - image: iteam1337/pm-engine
      context: packages/engine-elixir
    - image: iteam1337/pm-engine-server
      context: packages/engine-server
    - image: iteam1337/pm-engine-ui
      context: packages/engine-ui
deploy:
  kubectl:
    manifests:
      # TODO: Disabled since cars from simulator can't accept offers and it blocks the engine from processing items
      # - k8s/packages/booking-simulator.yaml
      # - k8s/packages/car-simulator.yaml

      - k8s/packages/booking-interface.yaml
      - k8s/packages/driver-interface.yaml
      - k8s/packages/engine.yaml
      - k8s/packages/engine-server.yaml
      - k8s/packages/engine-ui.yaml
      # TODO: Disabled because this should be done once and not redeployed every time
      # - k8s/rabbitmq.yaml
#    - k8s/osrm.yaml
#    - k8s/redis.yaml
#    - k8s/travis-rbac.yaml
#    - k8s/cert-manager/issuer.yaml
#    - k8s/cert-manager/map-certificate.yaml
#    - k8s/cert-manager/match-route-certificate.yaml
#    - k8s/traefik/traefik.yaml
