version: "3.5"
services:
  route-evaluation-graphhopper:
    build: .
    container_name: "pm_route_evaluation_graphhopper"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - predictivemovement

networks:
  predictivemovement:
    driver: bridge
    name: predictivemovement
