apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: signing-ui-ingress
  annotations:
    kubernetes.io/ingress.class: "public"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - signing.predictivemovement.se
      secretName: signing-ui-prod-tls
  rules:
    - host: signing.predictivemovement.se
      http:
        paths:
          - backend:
              serviceName: signing-ui
              servicePort: 80
