# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
  # - k8s/packages/dev/driver-interface.yaml
  - resources/engine.yaml
  # - k8s/packages/dev/engine-server.yaml
  # - k8s/packages/dev/engine-ui.yaml
  # - k8s/packages/dev/route-optimization-jsprit.yaml
  # - k8s/packages/dev/vehicle-offer.yaml
  # - k8s/packages/dev/auto-accept-offer.yaml
  # - k8s/packages/dev/booking-dispatcher.yaml

# namespace to deploy all Resources to
namespace: predictivemovement-dev
# labels added to all Resources
# commonLabels:
#   app: example
#   env: test

# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: engine-ui-ingress
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     cert-manager.io/cluster-issuer: "letsencrypt-prod"
# spec:
#   tls:
#     - hosts:
#         - engine-ui.iteamdev.io
#       secretName: engine-ui-prod-tls
#   rules:
#     - host: engine-ui.iteamdev.io
#       http:
#         paths:
#           - backend:
#               serviceName: engine-ui
#               servicePort: 80
# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: engine-ui-ingress
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     cert-manager.io/cluster-issuer: "letsencrypt-prod"
# spec:
#   tls:
#     - hosts:
#         - engine-ui.dev.iteamdev.io
#       secretName: engine-ui-prod-tls
#   rules:
#     - host: engine-ui.dev.iteamdev.io
#       http:
#         paths:
#           - backend:
#               serviceName: engine-ui
#               servicePort: 80
