apiVersion: apps/v1
kind: Deployment
metadata:
  name: map
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: map
  template:
    metadata:
      labels:
        app: map
    spec:
      containers:
      - image: iteam1337/predictive-movement-map
        name: web
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: google-token
        - secretRef:
            name: mapbox-token
        env:
        - name: API_HOST
          value: https://match-route.iteamdev.se
        ports:
        - containerPort: 4000
          protocol: TCP
        resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: map
  labels:
    app: map
spec:
  ports:
    - name: "80"
      protocol: TCP
      port: 80
      targetPort: 4000
  selector:
    app: map
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: map
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: map.iteamdev.se
      http:
        paths:
          - backend:
              serviceName: map
              servicePort: 80