apiVersion: v1
kind: Namespace
metadata:
  name:  serviceids
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  travis
  namespace: serviceids
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cicd-apps
rules:
- apiGroups: ["", "extensions", "apps"]
  resources:
  - deployments
  - deployments/scale
  - namespaces
  - pods
  - services
  - ingresses
  - replicasets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: travis-apps
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cicd-apps
subjects:
- kind: User
  name: system:serviceaccount:serviceids:travis
  apiGroup: rbac.authorization.k8s.io