apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: letsencrypt-prod
spec:
  secretName: letsencrypt-prod
  dnsNames:
    - "*.devops.iteamdev.se"
  acme:
    config:
      - dns01:
          ingressClass: traefik
          provider: route53
        domains:
          - "*.devops.iteamdev.se"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
