apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: register@iteam.se
    privateKeySecretRef:
      name: letsencrypt-prod
    dns01:
      providers:
        - name: route53
          route53:
            region: eu-north-1
            accessKeyID: AKIAIOHQJ2X7UR5VVBNA
            secretAccessKeySecretRef:
              name: amazon-web-service-credentials
              key: AWS_SECRET_ACCESS_KEY
