---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: map-letsencrypt-prod
spec:
  secretName: map-letsencrypt-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  acme:
    config:
    - http01:
        ingressClass: traefik
      domains:
      - map.pm.iteamdev.se
  dnsNames:
  - map.pm.iteamdev.se