---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: candidates-graphhopper
  namespace: predictivemovement
  labels:
    app: candidates-graphhopper
spec:
  selector:
    matchLabels:
      app: candidates-graphhopper
  template:
    metadata:
      labels:
        app: candidates-graphhopper
    spec:
      containers:
        - name: candidates-graphhopper
          image: iteam1337/pm-candidates-graphhopper
          env:
            - name: AMQP_HOST
              value: amqp://rabbitmq
