apiVersion: apps/v1
kind: Deployment
metadata:
  name: route-optimization-jsprit
  namespace: predictivemovement
  labels:
    app: route-optimization-jsprit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: route-optimization-jsprit
  template:
    metadata:
      labels:
        app: route-optimization-jsprit
    spec:
      containers:
        - name: route-optimization-jsprit
          image: iteam1337/pm-route-optimization-jsprit
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
          resources: {}
      restartPolicy: Always
