version: "3.5"
services:
  jupyter:
    build: .
    image: pm_route_evaluation/jupyter:1
    container_name: "pm_route_evaluation_jupyter"
    environment:
      - PYTHONPATH=/home/jovyan/work/src
      - JUPYTER_TOKEN=${PM_JUPYTER_TOKEN-f664b7779b19772730b6ff47509056a089e69304fa182ee6}
    ports:
      - "58881:8888"
    volumes:
      - ./..:/home/jovyan/work
