openapi: 3.0.0
servers:
  - url: http://localhost:8000
info:
  description: |
    This is the OpenAPI for Predictive Movement.
  version: 1.0.0-oas3
  title: Predictive Movement API
  contact:
    email: predictivemovement@iteam.se
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
paths:
  /transports:
    get:
      operationId: get_transports
      summary: Get all the transports to which you have access
      responses:
        "200":
          description: OK
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transport"
  /itinerary/{transport_id}:
    get:
      operationId: get_itinerary
      summary: Get an itinerary by transport ID
      parameters:
        - name: transport_id
          in: path
          description: ID of the transport to which the itinerary is assigned
          required: true
          schema:
            type: string
          example: "pmv-2314"
      responses:
        "200":
          description: OK
          content:
            application/json; charset=utf-8:
              schema:
                $ref: "#/components/schemas/Itinerary"
  /bookings:
    post:
      operationId: "create_booking"
      summary: Create a new booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                trip_id:
                  type: integer
                pickup:
                  $ref: "#/components/schemas/Address"
                delivery:
                  $ref: "#/components/schemas/Address"
                metadata:
                  type: object
                  properties: {}
                size:
                  type: object
                  properties:
                    weight:
                      type: number
                      description: Weight in kilograms
                      example: 1
                    dimensions:
                      $ref: "#/components/schemas/Dimensions"
                  required:
                    - weight
                    - dimensions
              required:
                - trip_id
                - pickup
                - delivery
                - metadata
                - size

            example:
              trip_id: 1
              pickup:
                city: "Stockholm"
                street: "Visättra Backe 6"
                name: "Visättra backe 6, Stockholm"
                position:
                  lon: 17.958416
                  lat: 59.215666
              delivery:
                city: "Trelleborg"
                name: "Götagatan 26, Trelleborg"
                street: "Götagatan 26"
                position:
                  lon: 13.166109
                  lat: 55.383959
              metadata: {}
              size: 
                weight: 1
                dimensions:
                  width: 100
                  height: 100
                  length: 100
      responses:
        "200":
          description: OK
          content:
            application/json; charset=utf-8:
              schema:
                $ref: "#/components/schemas/Booking"


components:
  schemas:
    Activity:
      type: object
      properties:
        id:
          nullable: false
          type: string
        booking_id:
          type: string
        distance:
          type: number
        duration:
          type: number
        type:
          type: string
          enum: [start, end, pickup, delivery]
        position:
          $ref: "#/components/schemas/Position"
      required:
        - id
        - booking_id
        - distance
        - duration
        - type
        - position
    Address:
      type: object
      properties:
        city:
          type: string
        street:
          type: string
        name:
          type: string
        position:
          $ref: "#/components/schemas/Position"
      required:
        - position
    Dimensions:
      type: object
      properties:
        width:
          type: number
        length:
          type: number
        height:
          type: number
    Transport:
      type: object
      properties:
        transport_id:
          type: string
        busy:
          type: boolean
        capacity:
          type: object
          properties:
            volume:
              type: number
            weight:
              type: number
        earliest_start:
          type: string
          format: date-time
        latest_end:
          type: string
          format: date-time
        metadata:
          type: object
        start_address:
          $ref: "#/components/schemas/Address"
        end_address:
          $ref: "#/components/schemas/Address"
    Booking:
      type: object
      properties:
        id:
          type: string
        trip_id:
          type: integer
        delivery:
          $ref: "#/components/schemas/Address"
        pickup:
          $ref: "#/components/schemas/Address"
        ship_date:
          type: string
          format: date
        status:
          type: string
          description: Order Status
          enum:
            - placed
            - approved
            - delivered
        details:
          $ref: "#/components/schemas/BookingDetails"
    BookingDetails:
      type: object
      properties:
        metadata:
          type: object
          properties:
            cargo:
              type: string
            fragile:
              type: boolean
              default: false
            recipient:
              type: object
              properties:
                contact:
                  type: string
                name:
                  type: string
                info:
                  type: string
            sender:
              type: object
              properties:
                contact:
                  type: string
                name:
                  type: string
                info:
                  type: string
        weight:
          type: number
        volume:
          type: number
        dimensions:
          $ref: "#/components/schemas/Dimensions"
        loading_meters:
          type: number
        quantity:
          type: integer
          format: int32
    Position:
      type: object
      required:
        - lon
        - lat
      properties:
        lon:
          type: number
          format: float
        lat:
          type: number
          format: float
    Plan:
      type: object
    Itinerary:
      type: object
      properties:
        transport_id:
          type: string
        route:
          type: object
        activities:
          type: array
          items:
            $ref: "#/components/schemas/Activity"
      xml:
        name: Trips
      required:
        - transport_id
        - route
        - activities
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
